name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      # Optional
      # - name: Run tests
      #   run: go test ./...

      - name: Get latest tag
        id: tag
        run: |
          git fetch --tags

          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)

          if [ -z "$LATEST_TAG" ]; then
            NEW_TAG="v0.0.1"
          else
            VERSION=${LATEST_TAG#v}

            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

            PATCH=$((PATCH + 1))

            NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          fi

          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git tag ${{ steps.tag.outputs.new_tag }}
          git push origin ${{ steps.tag.outputs.new_tag }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}